### PR TITLE
Add Native Windows build capability

### PR DESCRIPTION
**Pull request by hernandp**
Currently xemu can make Windows binaries from "real Linux/UNIX" by cross-compilation.  
By using MSYS2/MinGW environment, users can build native binaries (both in 32 and 64 bit flavors) for Windows systems without booting Linux or Windows Subsystem for Linux.   
Note that building under WSL should be similar.

Requirements are MSYS2/MinGW package found at http://www.msys2.org/.

Documentation in README added.

### CODE REVIEW

**Comment by sausagejohnson** [comment]
Thank you @hernandp !!

**Comment by lgblgblgb** [comment]
Sounds nice enough as we talked on it at the evening. Let me check this through at today evening, now I could only have a quick look, but looks nice anyway, thanks!

**Comment by lgblgblgb** [comment]
I would like to ask you kindly if you can try to checkout a whole new dev branch and apply your changes on that, and sending the pull request. Since now I can see, for example there is an bad file xemu/arch-sys-nativewin.h which should not exist, there is no ARCH dependent header file Xemu, it is maybe in the master branch, so probably it's just survived that you switched from master to dev ... That's why it would be useful to do clean checkout, applying the needed changes, and send a PR on that. I can be even seen that this PR also shows one for my merges between master and dev, a bit confusing this way, I'm afraid :-O Surely I can apply these changes myself too (in fact I can do it at my own too) but I guess it's important to make others sure that they can contribute directly too :) :) Hopefully you understand my points here. Thanks a lot!

**Comment by hernandp** [comment]
> I would like to ask you kindly if you can try to checkout a whole new dev branch and apply your changes on that, and sending the pull request. Since now I can see, for example there is an bad file xemu/arch-sys-nativewin.h which should not exist, there is no ARCH dependent header file Xemu, it is maybe in the master branch, so probably it's just survived that you switched from master to dev ... That's why it would be useful to do clean checkout, applying the needed changes, and send a PR on that. I can be even seen that this PR also shows one for my merges between master and dev, a bit confusing this way, I'm afraid :-O Surely I can apply these changes myself too (in fact I can do it at my own too) but I guess it's important to make others sure that they can contribute directly too :) :) Hopefully you understand my points here. Thanks a lot!

No problem with that !  I will recreate a clean PR 👍

**Comment by lgblgblgb** [comment]
Ok, then I close this PR, but surely it's more than OK to send me a new one :) Thanks for your understanding.

**Pull request closed without merging**
