### PR TITLE
#220: uartmon update (so xemu communicates better with m65/mega65_ftp/m65dbg)

### PR DESCRIPTION
**Pull request by gurcei**
Work done in relation to card #220.

There may be aspects that you're not too keen on (such as the two tcp ports opened), it was handy for me while debugging xemu <--> m65 and xemu <--> mega65_ftp conversation, but perhaps won't have a much wider audience than me (at the moment).

So I don't mind reverting that bit out, or perhaps other sections you make note of in your review.

### CODE REVIEW

**Comment by lgblgblgb** [comment]
Are you sure you want to send this against `merger` branch? I am not even sure if umon in works in `merger` since the main loop was seriously touched, and no possibility anymore to have paused emulation without serious issues, unlike in `next`. I thought you want to do against `next` till somehow umon has some remedy in `merger`, to be honest.

**Comment by gurcei** [comment]
Aah, I think I initially tried `next`, but then it didn't have the 'hot-registers' stuff in there (needed by 'm65', if I recall right), but then I noticed that 'hot-registers' stuff was inside `merger`, so opted for that one.

I guess I don't recall the backstory on the 'next' and 'merger' branches, and perhaps that 'hot-register' stuff will make its way into the 'next' branch eventually (or perhaps it has already happened already and I didn't realise).

Anyways, those were the motivations on choosing 'merger' at the time. But if 'hot-registers' has made its way into 'next' branch already, then I'm happy to jump ship to 'next' branch.

**Comment by lgblgblgb** [comment]
Hmm, it's a hard decision then ... `merger` is intended only for the VIC-IV changes merged not anything else (in fact, any other material there is just to make it easy to see differences compared to `next` in some regards). At the other hand, hot registers stuff is the scope of VIC-IV of course, since it's a VIC-IV notion. Also note, that `merger` will lose and contribution information on long term, as it's so full of small and stupid (not from your side!!!) commits, that it won't be merged to `next` ever in this form, "polluting" the commit log of the main project with all the non-sense (again, it's not meant about your work, but in VIC-IV based try&error kind of commits all the time). That is, `merger` is kind of "let's play with it" material, and the final move will be to **delete** `merger` without any really literal continuation there in terms of history of the code. I just say this, since I really don't want to hurt anybody who has the nice effort to contribute which then ends with commit in the final branches with my name anyway.

**Comment by lgblgblgb** [comment]
In addition to my previous comment: one solution can be (but it requires work from you, and not so "nice" solution) to resolve the problem I've described, is adopting your changes from the `next` only leaving out the VIC-IV branch specific needs (ie: hot registers) and applying those later, when `merger` is in the `next` already. I just try to figure out something sane here in this impossible situation :-/

**Comment by gurcei** [comment]
Yep, I'm ok with rebasing my branch onto 'next' branch, to assure those pieces of the puzzle are in place and await the hot-register stuff to come later.

I'm wondering if though, in the interim period,  maybe I could keep the effort branched off 'merger' too, just in-case there are other commits and improvements that could be made (beyond what is covered already).

**Comment by lgblgblgb** [comment]
Well, you can fork anything as you want ;) Just beware, that `merger` is very hot stuff (not in the sense of hot registers hehe, but about changing rapidly) and you may have hard time to always adjust your work for it. That's why merging into `merger` is problematic as well, as even the main emulation loop is subject it be changed where all the things happening in terms of umon handler call also the problem of "pause" mode, and so on.

**Comment by gurcei** [comment]
Okidoke, will take the following path with it:

- I'm creating a new `220-uartmon-update-on-next` branch (which branches off the `next` branch)
- It consists of completely cherry-picked commits from the `220-uartmon-update` branch (which was branched from `merger` branch)
- I'll close this PR and create a new PR for the `220-uartmon-update-on-next` branch.
- This can be merged back to 'next'
- In the interim period while awaiting hot-register logic to make its way into `next` branch, if I have any other extra improvements/commits I could make relating to xemu<-->m65/mega65_ftp, I'll temporarily put them in the older `220-uartmon-update` branch
- Upon hot-register stuff making it into `next` branch, I can make a new branch off that and cherry-pick my additional efforts across into that

**Pull request closed without merging**
