### PR TITLE
Moved uart_mon to common-sources. Added uart_mon into c65. Imprroved …

### PR DESCRIPTION
**Pull request by BensonRSI**
Hi there,
i did three major changes.
- moved uart_mon to common-sources
- included uart-mon into c65 also.
- moved the monitor-commands from mega65.c into uart_mon , so i don't have to double them for c65

As improvement i added a disassembler into the uart-mon. After each trace-step, the disassembled 
line is shown. Also "d addr" disassembles from memory

One other minor change, is the possibility to load a file called "expansion-ram.dat" into memory after
startup. 

Please incorporate the changes into the mainline, so it is available for all.

Cheers,
Benson

### CODE REVIEW

**Comment by lgblgblgb** [comment]
Wow, thanks for your effort, kinda neat :) However I have one issue with this, but it's kind of an organization question. Actually my plan is to try the monitor part as the absolute minimal in Xemu. It's because that interface is meant for m65dbg. So actually disassembly part and any other stuff would be better to be implemented there in one place only. It also helps for the "real Mega65" (ie the FPGA board) since the m65dbg then can be used with Xemu and with the "real thing" as well. Also it's more easy to extend m65dbg then to create new features without modifying (or upgrading, in case of a user, and not Xemu developer) Xemu itself. What I have imagined, that m65dbg should do disasm at its own, with querying Xemu (or the board!) for the memory dump first. Another idea was to actually implement another abstraction layer or so, libm65dbg ... Then one can implement a command line m65dbg (again, for Xemu and the board as well) or even a GUI based separated one and so on ... But it also basically means the some, to do "advanced debugging" things on the side of m65dbg related stuff, and not Xemu level. The other side of the story: uart-monitor part of mega65/Xemu is intended to be universal, that is not even for C65 support (as you did) but also other emulators in Xemu, even Z80 based computers as well. However since mega65 emulation target of Xemu is kinda lame, confusing and ugly code now, I didn't want to implement more universal yet, before deciding the more or less "final phase" of main emulation loop construction throughout  Xemu targets. Eg, there is an experimental (even not yet committed, I mean not the working one ...) feature to allow the emscripten target (that is, html/js output from Xemu source base, there is an example for this already, if you find that in the wiki in my repo), but that requires to modify the construction the timing loop more universal which may affect other things, for example how is the best way to provide the universal interface for the external monitor capability in Xemu. Another issue, that Xemu currently needs UNIX domain socket for communication which excludes Windows then. Well, sorry for the long answer :) But you can see, it's kind of a big mess now, in code level on my side, and even in my brain as plans :) I will try to find some time to review your PR though, to tell more. Hopefully it hasn't created a feeling for you, that I don't value your work, it's NOT the case, and thanks for your work a lot!

**Comment by lgblgblgb** [comment]
Well-well, I can write a LOT :) But what is the important part, to be more clear, which I always miss during my short novels :) uart-mon is actually not an Xemu feature! It's an M65 FPGA board feature what Xemu tries to emulate ... However what is the common part if m65dbg, so works like disasm - I think  - would be better to be implemented there. Still the uart-mon interface indeed, can be made global for more emulators than M65 only, that's fairly true, and in fact was a plan of mine as well (again: #11 ).

**Comment by gardners** [comment]
I'm in favour of this pull request.

**Comment by BensonRSI** [comment]
Hi LGB ,
thanks for the detailed answer, but first i had to put shame on me, because i forget to add the to changed files uart_mon.c and uart_mon.h. and now i saw that compilecheck fails for win32.

I totally understood the approach to keep the "debugging  intelligence" out of the emulator itself and move it to a host based program. At best with a Gui and all bells and whistles. 
But meanwhile I'm pretty lost when trying to do some programming on the C65, so i always wrote some markers to the memory, reseted and took the internal monitor to check where the programflow was running through. So singlestepping and breakpoints are my real favourites by now.

I will try to convince a coder i know, if he can write a little SDL-based GUI , to do the disassmbly, the memory-dump and stuff,  so it can be moved to there. I already made up my mind about a "step-over" function and that would be much easier offline.

Cheers,
Benson

**Comment by lgblgblgb** [comment]
Hi! Sorry for the delay ... It seems many things changed now, sorry about that too, but I'm afraid more will come ... About the "monitor" feature ... I really think, I should give up the named socket stuff, as it won't work on Windows at least. I would move to TCP/IP socket listening on local port. m65dbg or similar solution should use that, surely disasm etc should be implemented in m65dbg. But in a way that it's Xemu-wide, ie even Z80 targets, so the monitor component should 'tell' the connecting client what emulation is running on that listening port, so it can decide which features and how to enable at all or supported at all. Also, I am thinking to move on very rudimentary HTTP mode for this client, ie now chunking or HTTP keep alive, simple HTTP requests only. It sound insane, but m65dbg if handles that transparently then no problem! The benefit of this: some can write even a HTML/JS frontend so from a browser there is a full featured "monitor client" (surely it's OPTIONAL, still, an external monitor/debugger like modified m65dbg can be used!!!) with all the possibilities of the web technique, ie even graphical memory dump for "sprite hinting" bitmap show, whatever you can imagine. Surely, you can write a GUI client to do the same, but it's harder, and the 'web' method is a cross-platform GUI then already! Anyway one thing is sure: it MUSTN'T be a web-only stuff, some people would be angry to force this I guess :) so there should be at least a strictly command-line client for it (like m65dbg now, and it should also continue to support the "real" M65 board with 'real' serial port as well!), or even a native GUI client you mentioned here too. It would be just an additional plus, what can also be done. Since I am more or less OK with html/JS (I even write 8 bit computer emulations in pure JS), it wouldn't be a big deal for me at least. However this is only my opinion, some people may find this "strange" or even worse :) :)

**Comment by gardners** [comment]
Hello,

I am happy with whatever path you choose, provided that m65dbg still works
with it, even if you need to submit some changes to m65dbg for this.  Named
socket to TCP, should be as you say, quite easy to  do.

Paul.

**Comment by BensonRSI** [comment]
Hi LGB,
i also brought things a little bit forward, by now. I wrote a GUI for 
the uart-mon-interface, based on QT, so it should be
fine also at Windows. Another thing, i did, is to harmonize the uart-mon 
from xemu and the one from the hardware,
so they have a similar command-set ( "s" command for setting memory, for 
example). I also removed the disassembler, this is now in the gui.
Moving to a tcpip-socket should no big deal, but wasn't in my focus by 
now, since i'm not using windows.
Latest commit on my fork should reflect all the changes.

Nevertheless, i would stick to the idea to have the uart-mon also in the 
xemu-C65 and the other machines,
it makes development much easier, when you can load your binaries to the 
target and single-step through them.

I'm a little bit unsure, where to place the qt-debugger, currently it is 
in a private-git server. On one hand it would fit in the xemu-repository,
because it is bound to the uart-protocol, on the other hand, i have 
written it in a object-orientated-manner, so it can be easily adapted to 
other
processors and protocols. Maybe an own git-hub-repo should be the best.




Cheers,
Benson.



Am 09.04.2017 um 12:28 schrieb LGB:

**Comment by lgblgblgb** [comment]
Gardners: Thanks for your comment. Well, yes, AFAIK, the technical details about monitor connection between the client (eg m65dbg) and the emulator (Xemu) or even the board is not so much an issue for _most_ people, if it works and work in the same way as it was or something close at least :) It's only important change for people developing the monitor connection and such :) For you, the M65 board specific uart-mon interface can be interesting, if you really want to keep this way, or you plan *any* change, I don't know too much about that. But currently I would assume to use it as it is now, at least.

Benson: I can understand you, I don't use Windows at all either - I even haven't got windows at all and using cross-compilation on Linux to produce win32 and win64 executables :) However it seems many user would, and I "have to" accept the needs that people would use Windows quite often. Anyway playing and getting to know with cross compilation is also a nice "hobby". Don't misunderstand me, but I can't comment a GUI QT client too much, I don't like QT since it's C++ and I hate C++ (and OOP languages ... well, maybe except for Python, don't ask me why, it's just me ...) but surely it's my problem, and users wouldn't even bothered too much what programming language is used if it works and looks great :) :) I would really not try to write a GUI too much, to be honest, so if you're keen with that, it's already a big win for others/us too, I think. I would stick with command-line client for personal use, or some kind of web solution if it's really needed to be more than command-line interface. But that's good, to have multiple choices and views! I wouldn't think it would belong to Xemu "core" in any way, not even m65dbg belongs too. What Xemu should contain is the part of the "interface" (let it be named socket, or TCP/IP etc) the client is used for to connect to. And indeed, it should be project wide, so C65 emulator too, or in fact, according to my plans, every emulators even non-Commodore and non-65xx-CPU-based ones (it's another question if a given client can support disassembly etc for a Z80 based target in Xemu for example, but I would like to maintain the possibility at least at Xemu level, and then the others is up to the monitor clients). What I would found useful to create a "core" (maybe still outside of Xemu repository!) contains the very basic elements of a client, ie, connection to a real M65 board on serial port, or connection to a socket (Xemu) and similar primitives. Maybe disasm support should go here too (because then it's easy to have disasm in different clients no need to code it in every ones)! Then it's easy to write a native client (C/C++/etc) using these, even your QT client. For a possible web frontend, it's another story. If you are careful here, you can see, that with this scheme, the goal is to able to use a client with both of Xemu or the areal M65 board (now speaking only about Mega65 for a while)! It would be nice with your client too, btw! So my dream is more like a target-independent abstraction layer. Some other common "monitor client core library" items I can imagine is for example map/label file loading for at least common assemblers, at least CA65 from CC65 but maybe Ophis too (since it mega65-core project uses Ophis currenly, but planning to switch to CA65 once). Other things like Z80 assemblers etc are bit out-of-topic here, just to mentioned here as the Xemu-wide project level decision thinggy ... And btw, I wouldn't call this uart-mon anymore, it's kinda more abstracted stuff it can be, I would call simply Xemu/monitor, and uart-mon is kinda M65 board specific solution "only".

Using TCP/IP sockets and especially some "web friendly" protocol is useful for another purposes as well, I've already described. Traditionally, HTTP requests seems to be a bit problematic since it's a request-reply protocol not so much common with the persistent bi-directional connection what we have now. I am still thinking on this, however modern browsers knows something called "websockets" which is kinda what I would need.

**Comment by lgblgblgb** [comment]
Just to mention: now I am about rewriting almost all of the mega65 emulation internal parts, working on m65mem branch. Since many things will change, there is not so much point now even to try to put monitor features up-to-date till I am ready. Then the other major work is VIC-IV more features but it won't be so monitor dependent then. Anyway, since the commit of multi-op CPU-run mode, the monitor has a bug not allow to "catch" breakpoints normally as CPU emulator may not return after each opcode. That problem and things like this should be fixed after the mentioned work ...

**Comment by gardners** [comment]
ok.

**Comment by lgblgblgb** [comment]
Please refer pull request #54 (it's the live state of merging request would be from my m65mem to the master branch) about the on-going changes, so far, it's the biggest change in Xemu/M65 since it's "birth" and still not fully ready, but with very promising result, ie even now it uses half of the host CPU power on 48MHz M65 emulation than before, and better compatibility (ie, now it's possible to write I/O areas on the $FF 1meg-slice with the corresponding I/O mode unrelated to the $D000-area current I/O mode, etc). I just mention here as well, since that big change virtually breaks anything related to memory and I/O references including the proposed changes here.

**Comment by gardners** [comment]
Sounds good.

Paul.

**Comment by lgblgblgb** [comment]
I close this pull request, because the original monitor framework now totally unusable and incompatible (see conflicting files). I have less time, but I am about preparing the new (some of the bits of the TCP/IP communication framework is already committed) one, but it would require a new stuff on top of it, it will be ready to be tested at least.

The second issue: I saw nice things here, like DMA fractional stepping, but it goes into this pull request as well since it's still open and this way it's really confusing to have many (obsoleted, conflicting) changes mixed with new developments as well. Fractional stepping in Mega65 DMA is something I have some code already with the new DMA "skeleton" just not published (basically a larger data type and only higher bits used for the integer part, so the same source works for C65/M65, and no additional addition is needed for the fractional part).

**Pull request closed without merging**
